### ISSUE TITLE
Menu doesn't load

### ISSUE THREAD

**Issue by andyci** [Cheesebaron/MvxFragmentsAndHamburger#2]
Hi,

In the latest version of MvvmCross (3.5.1-alpha 1), the menu items don't load.  Can you point me in the right direction as to why this might be?

Thanks,

**Comment by Cheesebaron** [comment]
You have the source to both, you have a debugger, I suggest you use that to your advantage.

**Comment by andyci** [comment]
I figured it out shortly after I wrote this.  Code is commented out here for some reason:
https://github.com/Cheesebaron/MvxFragmentsAndHamburger/blob/master/MvxFragmentsAndHamburger/Droid/Views/BaseView.cs#L18

**Comment by Cheesebaron** [comment]
You should check the issues section for MvvmCross, you might find out why.
